function run_tests()
    %%

    tests = { ...
        @test_update_qr, ...
        @test_forward_backward_solve, ...
        @test_multiplier_line_search, ...
        @test_get_condensed_adjoint, ...
        @test_get_condensed_gradient, ...
        @test_get_condensed_hessian, ...
        @test_get_condensed_primal_feasibility, ...
        @test_get_condensed_quadratic_contraints, ...
        @test_condensed_predictor_corrector, ...
        @test_condensed_rompc_step, ...
    };

    for i = 1: length(tests)
        fprintf("run test %d/%d (@%s) ...", i, length(tests), char(tests{i}));
        result = tests{i}("test");

        if result.passed == true
            fprintf(" passed\n");
        else
            fprintf(" FAILED\n");
        end
    end
end
